node.name: node01
network.host: 0.0.0.0
cluster:
  name: cluster01
  initial_master_nodes: node01

# Enable security features
xpack:
  security.enabled: true
  license.self_generated.type: basic

# Encrypt HTTP-based API connections from Kibana, Logstash, Elastalert
xpack.security.http.ssl:
  enabled: true
  key: certs/elasticsearch.key
  certificate: certs/elasticsearch.crt
  certificate_authorities: certs/ca.crt

# Encrypt communication between Elasticsearch nodes
xpack.security.transport.ssl: 
  enabled: true
  key: certs/elasticsearch.key
  certificate: certs/elasticsearch.crt
  certificate_authorities: certs/ca.crt
  verification_mode: certificate