services:
  elasticsearch:
    build: elasticsearch
    image: elasticsearch:latest
    container_name: elasticsearch
    env_file:
      - elasticsearch/variables.env
    volumes:
      - certificates:/opt/elasticsearch/config/certs
    networks: 
    - elastic
    ports:
    - 9200:9200 
  
  elastalert:
    depends_on: 
      - elasticsearch
    build: elastalert
    image: elastalert:latest
    container_name: elastalert
    volumes:
      - certificates:/opt/elastalert/config/certs
    networks:
    - elastic

volumes:
  certificates:
    name: certificates
    driver: local

networks:
  elastic:
    name: elastic