services:
  elasticsearch:
    build: elasticsearch
    image: elasticsearch:latest
    container_name: elasticsearch
    env_file:
      - .env
    volumes:
      - certs:/opt/elasticsearch/config/certs/
    networks: 
      elastic:
        ipv4_address: ${ELASTICSEARCH_IP}
    ports:
      - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT} 
    extra_hosts:
      - "elasticsearch:${ELASTICSEARCH_IP}"
    healthcheck:
      test: ["CMD-SHELL", "curl --cacert config/certs/ca.crt -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD} https://${ELASTICSEARCH_IP}:9200/"]
      start_period: 30s
      retries: 2
  elastalert:
    depends_on: 
      elasticsearch:
        condition: "service_healthy"
    build: elastalert
    image: elastalert:latest
    container_name: elastalert
    volumes:
      - certs:/opt/elastalert/config/certs/
    networks: 
      elastic:
        ipv4_address: ${ELASTALERT_IP}
    extra_hosts:
      - "elasticsearch:${ELASTICSEARCH_IP}"
volumes:
  certs:
    name: certs
networks:
  elastic:
    name: elastic
    ipam: 
      config: 
        - subnet: ${SUBNET}