services:
  elasticsearch:
    build: elasticsearch
    image: elasticsearch:latest
    container_name: elasticsearch
    env_file:
      - .env
    volumes:
      - certs:/opt/elasticsearch/config/certs/
    networks: 
      elastic:
        ipv4_address: ${ELASTICSEARCH_IP}
    extra_hosts:
      - elasticsearch:${ELASTICSEARCH_IP}
    ports:
      - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT} 
#    healthcheck:
#      test: ["CMD", "curl", "--cacert", "config/certs/ca.crt", "https://elasticsearch:9200"]
#      start_period: 30s
#      interval: 20s
#      timeout: 10s
#      retries: 6
  elastalert:
    depends_on: 
      - elasticsearch
    build: elastalert
    image: elastalert:latest
    container_name: elastalert
    volumes:
      - certs:/opt/elastalert/config/certs/
    networks: 
      elastic:
        ipv4_address: ${ELASTALERT_IP}
    extra_hosts:
      - elasticsearch:${ELASTICSEARCH_IP}
volumes:
  certs:
    name: certs
networks:
  elastic:
    name: elastic
    ipam: 
      config: 
        - subnet: ${SUBNET}