services:
  elasticsearch:
    build: elasticsearch
    image: docker-elastic/elasticsearch:v1.0.0
    container_name: elasticsearch
    env_file:
      - .env
    volumes:
      - certs:/usr/share/elasticsearch/config/certs/
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    build: kibana
    image: docker-elastic/kibana:v1.0.0
    container_name: kibana
    env_file:
      - .env
    volumes:
      - certs:/usr/share/kibana/config/certs/
    ports:
      - 5601:5601
    networks:
      - elastic
  logstash:
    build: logstash
    image: docker-elastic/logstash:v1.0.0
    container_name: logstash
    env_file:
      - .env
    volumes:
      - certs:/usr/share/logstash/config/certs/
    ports:
      - 5044:5044
      - 9600:9600
    networks:
      - elastic
volumes:
  certs:
    name: certs
networks:
  elastic:
    name: elastic