services:
  elasticsearch:
    build: elasticsearch
    image: docker-elastic/elasticsearch:v1.0.0
    container_name: elasticsearch
    env_file:
      - .env
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - certs:/usr/share/elasticsearch/config/certs/
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    healthcheck:
      test: [ "CMD-SHELL", "curl -s --cacert config/certs/ca.crt https://elasticsearch:9200 | grep -q 'missing authentication credentials'" ]
  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    build: kibana
    image: docker-elastic/kibana:v1.0.0
    container_name: kibana
    env_file:
      - .env
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - certs:/usr/share/kibana/config/certs/
      - kibana:/usr/share/kibana/data
    ports:
      - 5601:5601
    networks:
      - elastic
  #logstash:
  #  depends_on:
  #    elasticsearch:
  #      condition: service_healthy
  #  build: logstash
  #  image: docker-elastic/logstash:v1.0.0
  #  container_name: logstash
  #  env_file:
  #    - .env
  #  volumes:
  #    - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
  #    - certs:/usr/share/logstash/config/certs/
  #  ports:
  #    - 5044:5044
  #    - 9600:9600
  #  networks:
  #    - elastic
volumes:
  certs:
    name: certs
  elasticsearch:
    name: elasticsearch
  kibana:
    name: kibana
networks:
  elastic:
    name: elastic