cluster:
  name: "cluster_01"
node:
  name: "node_01"
discovery:
  type: single-node
network:
  host: 0.0.0.0
xpack:
  license:
    self_generated:
      type: "basic"
  security:
    enabled: true 
    http.ssl:                               # Encrypt HTTP-based API connections from Kibana, Logstash, etc.
      enabled: true
      certificate_authorities: certs/ca.crt
      certificate: certs/elasticsearch.crt
      key: certs/elasticsearch.key
      verification_mode: certificate
    transport.ssl:                          # Encrypt communication between Elasticsearch nodes
      enabled: true
      certificate_authorities: certs/ca.crt
      certificate: certs/elasticsearch.crt
      key: certs/elasticsearch.key
      verification_mode: certificate